### PR TITLE
Footer added

### PR DESCRIPTION
**Pull request by Hrithikshetty**

### CODE REVIEW

**Comment by Hrithikshetty** [comment]
footer added

**Comment by Nandini80** [comment]
Provide an image of the footer.

**Comment by Hrithikshetty** [comment]
GitHub Education and 15 more pages - Personal - Microsoft​ Edge 01-03-2024 02_28_28

**Comment by Hrithikshetty** [comment]
React App and 2 more pages - Personal - Microsoft​ Edge 21-03-2024 11_32_41
 IMAGE OF FOOTER

**Comment by Nandini80** [comment]
Remove the cityplus logo and on clicking Privacy Policy open terms and condition page and remove Terms of Service.

**Comment by Nandini80** [comment]
Are you going to make changes or not?

**Comment by Nandini80** [comment]
There are conflicts with your PR because I pushed new PR's as you took a lot of time. Please sync your cloned repository first and then resolve the conflicts.

**Pull request closed without merging**
