### PR TITLE
Fixed #11

### LINKED ISSUE #11: Issue with Form Submission: Cannot POST /Signup
When attempting to submit the login and signup forms in the application, I encounter an error message stating "Cannot POST /Signup". This issue prevents users from successfully logging in or signing up, hindering the functionality of the application.

Instead of processing the form submission as expected, users encounter an error message indicating "Cannot POST /Signup". This suggests a breakdown in the communication between the client-side form submission and the server-side endpoint handling. There may be issues related to the client-side request format or the server's inability to handle the POST request properly.

Web capture_18-3-2024_3240_localhost
Web capture_18-3-2024_3216_localhost

### PR DESCRIPTION
**Pull request by Adii2202**

### CODE REVIEW

**Comment by Nandini80** [comment]
issue #11 is already fixed

**Comment by Adii2202** [comment]
The issue isn't fixed u may try once

**Comment by Nandini80** [comment]
yes you are right

**Comment by Nandini80** [comment]
df

**Comment by Adii2202** [comment]
when i tried this the signup wasn't working, it was alerting error msgs but if its done then its ok.

**Comment by Nandini80** [comment]
Let me open this issue again.
If you want i will assign this issue to you.

**Pull request closed without merging**
