### PR TITLE
Fixed #19 Fixed #17

### LINKED ISSUE #17: Signup/Login issue

### LINKED ISSUE #19: CORS is not setup
image

Need to setup CORS

### PR DESCRIPTION
**Pull request by Adii2202**
Fixed #19 
Fixed #17 
Fixed the Current user not showing error

Interceptor Code had error - 
privateReq.interceptors.request.use(
  (config) => {
    const token = localStorage.getItem("token");
    if (token) {
      config.headers["Authorization"] = `${token}`;
    }
    return config;
  },
  (error) => {
    return Promise.reject(error);
  }
);

### CODE REVIEW

**Comment by Gursimranjeet-Singh** [comment]
wasn't  it working without cors? because the server is rendering client side so both of them are on same port so there should not be any issue  regarding cors?

**Comment by Nandini80** [comment]
@Adii2202 Provide a video in which signup and login is working correctly.

**Comment by Adii2202** [comment]
@Gursimranjeet-Singh the links are not working on same port they need the port 2000 which is ur backend server

**Comment by Adii2202** [comment]
@Nandini80 
[React App - Google Chrome 2024-03-21 19-27-21.zip](https://github.com/Nandini80/CityPlus/files/14696204/React.App.-.Google.Chrome.2024-03-21.19-27-21.zip)

**Comment by Gursimranjeet-Singh** [comment]
@Adii2202 I understand that the link needs to request the port of the server. But I am concerned about the absolute path you have mentioned localhost:2000 in the request won't this create an error when we run on any other port? can you verify it by running it on another port once without changing the localhost:2000 request from the client side?

**Comment by Adii2202** [comment]
its on u on which port u wanna run i tried running it on 2000 the requests worked cuz if u wanna run the frontend and backend on same port u need a proxy server and its not mentioned

**Comment by Adii2202** [comment]
i just forked the repo again and tried and then i saw, if the issue is solved then y is this happening

**Comment by Nandini80** [comment]
I am receiving an error indicating that the port is already in use. Even after changing to a different port, I continue to encounter the same issue.

**Comment by Adii2202** [comment]
its running on my pc

**Comment by Adii2202** [comment]
idk wts the problem then u can close the pr

**Comment by Nandini80** [comment]
Try running it on the workspace and if there is anything left to commit then do it.

**Comment by Adii2202** [comment]
Its working on my side

**Comment by Adii2202** [comment]
check the req once on thunderclient or postman when we use 2000 port then only its working else not

**Pull request merged**
